language: android
jdk: oraclejdk7

branches:
  only:
    - master
  except:
    # disable all branches while Travis is not stable

env:
  matrix:
    - ANDROID_TARGET=android-16 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22 - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23 - ANDROID_ABI=armeabi-v7a
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra
    #- addon
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-16

    #- sys-img-armeabi-v7a-android-19
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 20
  - adb shell input keyevent 82 &

#before_script:
#  #- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
#  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  #- android-wait-for-emulator
#  #- adb shell input keyevent 82 &

script:
   - ./gradlew connectedAndroidTest -PdisablePreDex --continue --info

#script:
#  #- android list target
#  - ./gradlew assembleDebug -PdisablePreDex
#  - ./gradlew assembleAndroidTest -PdisablePreDex
#
#  - android-wait-for-emulator
#  - adb devices
#  - adb shell input keyevent 82 &
#
#  - adb install -r app/build/outputs/apk/app-debug.apk
#  - adb install -r app/build/outputs/apk/app-debug-androidTest-unaligned.apk
#
#  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' > screen.png
  - ./imgurbash.sh screen.png
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'





